# -*- fill-column: 1000 -*-
kind: pipeline
name: on_push

volumes:
- name: debian-package-cache
  host:
    path: /var/cache/debian-package-cache

trigger:
  event:
    exclude:
    - tag

steps:
- name: GCC 8 / clang 7
  image: debian:buster-slim
  pull: always
  environment:
    CXX: g++-8
    CXXFLAGS: -pipe -O2
    LANG: en_US.utf-8
    DEBIAN_FRONTEND: noninteractive
  commands:
  - rm /etc/apt/apt.conf.d/docker-clean
  - alias apt-get='rm -f /var/cache/apt/archives/lock && apt-get'
  - apt-get update -q
  - apt-get install -qq build-essential clang cmake pkg-config catch libcurl4-openssl-dev libjsoncpp-dev asciidoc
  - rm -rf build && mkdir -p build && cd build
  - cmake -DWITH_TESTS=yes ..
  - cmake --build .
  - cd tests && ctest -V
  - cd ../../
  - rm -rf build && mkdir -p build && cd build
  - CXX="clang++" cmake -DWITH_TESTS=yes ..
  - cmake --build .
  - cd tests && ctest -V
  - make install
  volumes:
  - name: debian-package-cache
    path: /var/cache/apt/archives

- name: notify
  image: drillster/drone-email
  pull: always
  settings:
    host: mail.tzend.de
    from: drone@tzend.de
    username:
      from_secret: email_username
    password:
      from_secret: email_password
  when:
    status: [ changed, failure ]
